// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_0eNU7_Zcoy_iD8TE-zXAfzvMIf0GBw',
    appId: '1:951579532657:web:5d817bf3ba7326c2d2ead0',
    messagingSenderId: '951579532657',
    projectId: 'vintage4-4e212',
    authDomain: 'vintage4-4e212.firebaseapp.com',
    storageBucket: 'vintage4-4e212.appspot.com',
    measurementId: 'G-KZEHE87679',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLkJ02gQaaG5eCyJI5JTVsFuyL30ymFI',
    appId: '1:951579532657:android:50aa2bed8705c6e7d2ead0',
    messagingSenderId: '951579532657',
    projectId: 'vintage4-4e212',
    storageBucket: 'vintage4-4e212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2dC0NmnyrkQteAb1XVBkHpjJ835c31Nw',
    appId: '1:951579532657:ios:c9b5007ed52443aed2ead0',
    messagingSenderId: '951579532657',
    projectId: 'vintage4-4e212',
    storageBucket: 'vintage4-4e212.appspot.com',
    androidClientId: '951579532657-ddktp9vcsfle0tpcb0k9cnv27dtbvug9.apps.googleusercontent.com',
    iosClientId: '951579532657-htattjpbru8p9joh41m3us9cv8re4gvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2dC0NmnyrkQteAb1XVBkHpjJ835c31Nw',
    appId: '1:951579532657:ios:fad5857b4dd29fe8d2ead0',
    messagingSenderId: '951579532657',
    projectId: 'vintage4-4e212',
    storageBucket: 'vintage4-4e212.appspot.com',
    androidClientId: '951579532657-ddktp9vcsfle0tpcb0k9cnv27dtbvug9.apps.googleusercontent.com',
    iosClientId: '951579532657-t81pc6suapmglq4bpbgk7ls9rte6rnut.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
